---
# defaults file for tacacs

tacacs_server_primary_name: ISE-TACACS
tacacs_server_primary_ip: 10.0.0.10
tacacs_server_secondary_name: ISE-TACACS
tacacs_server_secondary_ip: 10.0.0.11

tacacs_server_group: ISE-GRP-TACACS
tacacs_server_key: TopSecret
