---
# tasks file for dhcp_snooping

- name: configure_cisco.ios.ios | Gather facts.
  cisco.ios.ios_facts:
    gather_subset:
      - min
    gather_network_resources:
      - l2_interfaces

- name: configure_cisco.ios.ios | Designate all trunk ports as trusted.
  cisco.ios.ios_config:
    lines:
      - ip dhcp snooping trust
    parents:
      - interface {{ dhcp_snooping_item['name'] }}
  when:
    - dhcp_snooping_item['mode'] is defined
    - dhcp_snooping_item['mode'] == 'trunk'
  loop: "{{ ansible_facts['network_resources']['l2_interfaces'] }}"
  loop_control:
    loop_var: dhcp_snooping_item
    label: "{{ dhcp_snooping_item['name'] }}"
  notify: Save ios.

- name: configure_cisco.ios.ios | Enable dhcp snooping in all vlans.
  cisco.ios.ios_config:
    lines:
      - ip dhcp snooping
      - ip dhcp snooping vlan 1-4094
  notify: Save ios.
