---
# tasks file for software

- name: check | Gather facts.
  cisco.ios.ios_facts:
    gather_subset:
      - min

- name: check | Print software compliance.
  ansible.builtin.debug:
    msg: "Installed {{ ansible_facts['net_system'] }} is {{ ansible_facts['net_version'] }}. Compliant version is {{ software_version }}."
    verbosity: 0
  when: not ansible_check_mode

- name: check | Assert software compliance.
  ansible.builtin.assert:
    that:
      - "ansible_facts['net_version'] is ansible.builtin.version(software_version)"
    success_msg: "Compliant {{ ansible_facts['net_system'] }} {{ ansible_facts['net_version'] }} is installed."
    fail_msg: "Installed {{ ansible_facts['net_system'] }} is {{ ansible_facts['net_version'] }}. Upgrade to {{ software_version }} is required."
  when: ansible_check_mode | ansible.builtin.bool
