---
# tasks file for sofware

- name: install | Install IOS.
  when:
    - ansible_network_os is eq('cisco.ios.ios')
    - ansible_facts['net_iostype'] is eq('IOS')
  block:

    - name: install | Set boot variable. Copy running-config startup-config.
      cisco.ios.ios_config:
        lines:
          - boot system flash:{{ software_image }}
        save_when: always

    - name: install | Install compliant IOS and reboot.
      cisco.ios.ios_command:
        commands:
          - command: reload reason Upgrade {{ ansible_facts['net_system'] }} to {{ software_version }}
            prompt: Proceed with reload
            answer: "\r"
      register: software_installed

    - name: install | Wait for device to reboot.
      ansible.builtin.wait_for_connection:
        delay: 60
        timeout: 1800


- name: install | Install IOS-XE.
  when:
    - ansible_network_os is eq('cisco.ios.ios')
    - ansible_facts['net_iostype'] is eq('IOS-XE')
  block:

    - name: install | Set boot variable and enable auto-boot. Copy running-config startup-config.
      cisco.ios.ios_config:
        lines:
          - no boot system all
          - boot system flash:packages.conf
          - no boot manual
        save_when: always

    - name: install | Install compliant OS and reboot.
      cisco.ios.ios_command:
        commands:
          - install add file flash:{{ software_image }} activate commit prompt-level none
      vars:
        ansible_command_timeout: 3600
      register: software_installed

  rescue:

    - name: install | Reset the connection.
      ansible.builtin.meta: reset_connection

  always:

    - name: install | Wait for device to reboot.
      ansible.builtin.wait_for_connection:
        delay: 90
        timeout: 600


- name: install | Install NXOS.
  when: ansible_network_os is eq('cisco.nxos.nxos')
  block:

    - name: install | Copy running-config startup-config.
      cisco.nxos.nxos_config:
        save_when: always

    - name: install | Disruptively install compliant OS.
      cisco.nxos.nxos_command:
        commands: >-
          install all nxos bootflash:{{ software_image }}
          {{ (software_issu | ansible.builtin.bool) | ansible.builtin.ternary('non-disruptive', 'non-interruptive') }}
      vars:
        ansible_command_timeout: 3600
      register: software_installed

  rescue:

    - name: install | Reset the connection.
      ansible.builtin.meta: reset_connection

  always:

    - name: install | Wait for device to reboot.
      ansible.builtin.wait_for_connection:
        delay: 90
        timeout: 600


- name: install | Assert the software upgrade.
  when: software_installed is defined
  block:

    - name: install | Gather facts.
      cisco.ios.ios_facts:
        gather_subset: min
      until: not software_result['failed']
      retries: 5
      delay: 10
      register: software_result

    - name: install | Assert that the software upgrade succeeded.
      ansible.builtin.assert:
        that: ansible_facts['net_version'] is ansible.builtin.version(software_version)
        success_msg: Upgrade to {{ software_version }} was successful.
        fail_msg: Unable to upgrade. Device is running {{ ansible_facts['net_version'] }}. Expected {{ software_version }}.
