---
# tasks file for software

- name: Include tasks for checking software compliance.
  tags: upload
  ansible.builtin.include_tasks:
    file: check.yml
    apply:
      tags:
        - upload

- name: Include tasks for uploading software to target.
  tags: upload
  ansible.builtin.include_tasks:
    file: upload.yml
    apply:
      tags:
        - upload
  when:
    - not ansible_check_mode
    - ansible_facts['net_version'] is not ansible.builtin.version(software_version)

- name: Include tasks for upgrading software.
  ansible.builtin.include_tasks:
    file: install.yml
  when:
    - not ansible_check_mode
    - ansible_facts['net_version'] is not ansible.builtin.version(software_version)

- name: Include tasks for scheduling the software upgrade.
  tags: [never, schedule]
  ansible.builtin.import_tasks:
    file: schedule_upgrade.yml
  when: not ansible_check_mode
  delegate_to: localhost
  run_once: true
