---
# tasks file for software

- name: Gather facts.
  tags: upload
  cisco.ios.ios_facts:
    gather_subset:
      - min

- name: Include tasks for uploading software to target.
  tags: upload
  ansible.builtin.include_tasks:
    file: upload.yml
    apply:
      tags:
        - upload
  when: ansible_facts['net_version'] is not ansible.builtin.version(software_version)

- name: Include tasks for upgrading software.
  ansible.builtin.include_tasks:
    file: install.yml
  when: ansible_facts['net_version'] is not ansible.builtin.version(software_version)
