---
# tasks file for software

- name: schedule_upgrade | Pause to get input.
  ansible.builtin.pause:
    prompt: "Enter the number of minutes in which to schedule upgrade for {{ software_target }}"
  register: __software_input

- name: schedule_upgrade | Schedule upgrade.
  ansible.posix.at:
    command: "cd {{ playbook_dir }} && ansible-playbook {{ software_playbook_name }} -e 'target={{ software_target }}'"
    count: "{{ __software_input['user_input'] }}"
    units: minutes
    state: present

- name: schedule_upgrade | Print information.
  ansible.builtin.debug:
    msg: |-
      Use command 'atq' to view a list of all scheduled jobs.
      Use command 'at -c jobnumber' to view the content of a scheduled job.
      Use command 'atrm jobnumber' to cancel a scheduled job.
      View result at /var/spool/mail/{{ ansible_user }} once the job has completed.
    verbosity: 0
