---
# Automated release playbook for Ansible Collections.
#
# Meant to be used in a git CI/CD pipeline.
#
# Usage:
#   ansible-playbook .galaxy-deploy.yml -i localhost

- name: Deploy Ansible Collection to Ansible Galaxy.
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    namespace: jiholland
    collection: cisco
    galaxy_token: "{{ lookup('env', 'ANSIBLE_GALAXY_TOKEN') }}"

  tasks:

    - name: Assert that ANSIBLE_GALAXY_TOKEN is set.
      ansible.builtin.assert:
        that: galaxy_token != 0
        msg: A valid ANSIBLE_GALAXY_TOKEN must be set.

    - name: Get current git tag.
      # noqa command-instead-of-module
      ansible.builtin.shell: |-
        git describe --tags $(git rev-list --tags --max-count=1)
      changed_when: false
      register: release_tag

    - name: Lint changelog
      ansible.builtin.command: antsibull-changelog lint

    - name: Generate changelog for the release.
      ansible.builtin.command: antsibull-changelog release

    - name: Ensure the galaxy.yml tag is up to date.
      ansible.builtin.lineinfile:
        path: galaxy.yml
        regexp: "^version:"
        line: "version: {{ release_tag['stdout'] }}"

    - name: Push changelog to git.
      # noqa command-instead-of-module
      ansible.builtin.command: "{{ item }}"
      loop:
        - git config --global user.name ${{ env.USER }}
        - git config --global user.email ${{ env.USER }}@icloud.com
        - git commit -am "Update changelog and galaxy.yml for new release."
        - git push

    - name: Build the collection tarball.
      ansible.builtin.command:
        cmd: ansible-galaxy collection build
      changed_when: true
      notify: Remove collection tarball.

    - name: Publish the collection Ansible Galaxy.
      ansible.builtin.command: >
        ansible-galaxy collection publish --token {{ galaxy_token }}
        ./{{ namespace }}-{{ collection }}-{{ release_tag['stdout'] }}.tar.gz
      changed_when: true

  handlers:

    - name: Remove collection tarball.
      ansible.builtin.file:
        path: ./{{ namespace }}-{{ collection }}-{{ release_tag['stdout'] }}.tar.gz
        state: absent
