---
namespace: jiholland
name: cisco
version: 25.3.0
readme: README.md

authors:
  - Jørn Ivar Holland

description: "This collection includes helpful Ansible roles and content to help with Cisco network automation."

license:
  - BSD-3-Clause

tags:
  - backup
  - catalyst
  - cisco
  - interface_description
  - networking
  - software
  - tacacs

dependencies:
  cisco.ios: ">=9.0.0"
  cisco.nxos: ">=9.0.0"

repository: "https://github.com/jiholland/ansible-collection_cisco"
issues: "https://github.com/jiholland/ansible-collection_cisco/issues"

build_ignore: []
