---
namespace: jiholland
name: cisco
version: 23.0.0
readme: README.md

authors:
  - Jørn Ivar Holland

description: This collection includes helpful Ansible roles and content to help with Cisco network automation.

license:
  - BSD-3-Clause

tags:
  - networking

dependencies:
  ansible.posix: ">=1.5.4"
  cisco.ios: ">=5.1.0"
  cisco.nxos: ">=5.2.1"
  community.general: ">=7.5.0"

repository: https://github.com/jiholland/ansible-collection_cisco
documentation: https://github.com/jiholland/ansible-collection_cisco
homepage: https://github.com/jiholland
issues: https://github.com/jiholland/ansible-collection_cisco/issues

build_ignore: []
