---
# defaults file for upgrade

# The server where the compliant images are stored.
upgrade_tftp_server: "{{ tftp_server | default('10.191.163.11') }}"

# Overwrite the defaults with the values from inventory
upgrade_compliant_version: "{{ lookup('ansible.builtin.template', 'upgrade_compliant_version.j2') | ansible.builtin.from_yaml }}"
upgrade_compliant_image: "{{ lookup('ansible.builtin.template', 'upgrade_compliant_image.j2') | ansible.builtin.from_yaml }}"

# List containing compliant versions and images for each system.
# These are used to set the upgrade_compliant_version and upgrade_compliant_image defaults above.
upgrade_compliance:
  - system: ios
    model: '^C9[3-6][0-9][0-9]'  # Catalyst 9300, 9407, 9410, 9500, 9600
    compliant_version: 17.06.05
    compliant_image: cat9k_iosxe.17.06.05.SPA.bin

  - system: ios
    model: '^WS-C2960CX'
    compliant_version: 15.2(7)E5
    compliant_image: c2960cx-universalk9-mz.152-7.E5.bin

  - system: nxos
    model: '^Nexus9000'
    compliant_version: 10.2(5)
    compliant_image: nxos64-cs.10.2.5.M.bin

# Used when scheduling the upgrade
upgrade_playbook_name: playbook_upgrade.yml

# Cisco Nexus related defaults
upgrade_nexus:
  remote_file: /var/lib/tftpboot/{{ upgrade_compliant_image }}
  remote_scp_server: "{{ upgrade_tftp_server }}"
  remote_scp_server_user: "{{ ansible_user }}"
  remote_scp_server_password: "{{ ansible_password }}"
  vrf: management
  issu: false  # Upgrade using In Service Software Upgrade (ISSU)
