---
# defaults file for upgrade

upgrade_tftp_server: "{{ (tftp_server is defined) | ternary(tftp_server, '10.10.10.10') }}"

upgrade_mgmt_vrf: management

# Used when scheduling the upgrade
upgrade_playbook_name: playbook_upgrade.yml
