---
# defaults file for upgrade

upgrade_tftp_server: 10.0.0.1

upgrade_mgmt_vrf: management

upgrade_compliance:
  - system: ios
    model: '^C9[3-6][0-9][0-9]'  # Catalyst 9300, 9407, 9410, 9500, 9600
    compliant_version: 17.06.04
    compliant_image: cat9k_iosxe.17.06.04.SPA.bin

  - system: ios
    model: '^WS-C2960CX'
    compliant_version: 15.2(7)E5
    compliant_image: c2960cx-universalk9-mz.152-7.E5.bin

  - system: nxos
    model: '^Nexus9000'
    compliant_version: 10.2(4)
    compliant_image: nxos64-cs.10.2.4.M.bin
