---
# tasks file for vxlan_evpn

- name: dci_underlay | Enable and set DCI interfaces in L3 mode. Ensure jumbo MTU.
  cisco.nxos.nxos_interfaces:
    config:
      - name: "{{ vxlan_evpn_item.name }}"
        mode: layer3
        enabled: true
        mtu: "{{ vxlan_evpn_mtu }}"
    state: merged
  loop: "{{ dci_interfaces }}"
  loop_control:
    loop_var: vxlan_evpn_item
    label: "{{ vxlan_evpn_item.name }}"
  notify: Save nxos.

- name: dci_underlay | Ensure medium p2p for DCI interfacs.
  cisco.nxos.nxos_config:
    lines:
      - medium p2p
    parents:
      - interface {{ vxlan_evpn_item.name }}
  loop: "{{ dci_interfaces }}"
  loop_control:
    loop_var: vxlan_evpn_item
    label: "{{ vxlan_evpn_item.name }}"
  notify: Save nxos.

- name: dci_underlay | Assign IP address to DCI interfaces.
  cisco.nxos.nxos_l3_interfaces:
    config:
      - name: "{{ vxlan_evpn_item.name }}"
        ipv4:
          - address: "{{ vxlan_evpn_item.ip }}/31"
            tag: "{{ vxlan_evpn_rmap_redist_direct_tag }}"
    state: merged
  loop: "{{ dci_interfaces }}"
  loop_control:
    loop_var: vxlan_evpn_item
    label: "{{ vxlan_evpn_item.name }}"
  notify: Save nxos.

- name: dci_underlay | Configure remote border-leafs as neighbors under BGP process.
  cisco.nxos.nxos_bgp_global:
    config:
      as_number: "{{ bgp_asn }}"
      router_id: "{{ rid_ip }}"
      neighbors:
        - neighbor_address: "{{ vxlan_evpn_item.bgp_neighbor_ip }}"
          remote_as: "{{ vxlan_evpn_item.bgp_remote_asn }}"
          description: "{{ vxlan_evpn_item.bgp_neighbor_name }}"
          update_source: "{{ vxlan_evpn_item.name }}"
    state: merged
  loop: "{{ dci_interfaces }}"
  loop_control:
    loop_var: vxlan_evpn_item
    label: BGP neighbor {{ vxlan_evpn_item.bgp_neighbor_name }}
  notify: Save nxos.

- name: dci_underlay | Set address-family to IPv4-unicast for border-leaf neighbors under BGP process.
  cisco.nxos.nxos_bgp_neighbor_address_family:
    config:
      as_number: "{{ bgp_asn }}"
      neighbors:
        - neighbor_address: "{{ vxlan_evpn_item.bgp_neighbor_ip }}"
          address_family:
            - afi: ipv4
              safi: unicast
    state: merged
  loop: "{{ dci_interfaces }}"
  loop_control:
    loop_var: vxlan_evpn_item
    label: BGP neighbor {{ vxlan_evpn_item.bgp_neighbor_name }}
  notify: Save nxos.

- name: dci_underlay | Create route-map for redistribution of directly connected routes.
  cisco.nxos.nxos_route_maps:
    config:
      - route_map: "{{ vxlan_evpn_rmap_redist_direct_name }}"
        entries:
          - sequence: 10
            action: permit
            match:
              tags: "{{ vxlan_evpn_rmap_redist_direct_tag }}"
    state: merged
  notify: Save nxos.

- name: dci_underlay | Redistribute route-map in IPv4 address-family under BGP. Enable forwarding over multiple paths.
  cisco.nxos.nxos_bgp_address_family:
    config:
      as_number: "{{ bgp_asn }}"
      address_family:
        - afi: ipv4
          safi: unicast
          maximum_paths:
            parallel_paths: 4
          redistribute:
            - protocol: direct
              route_map: "{{ vxlan_evpn_rmap_redist_direct_name }}"
    state: merged
  notify: Save nxos.
