objects:
  role:
    backup:
      description: null
      name: backup
      version_added: null
    interface_description:
      description: null
      name: interface_description
      version_added: null
    software:
      description: null
      name: software
      version_added: null
    tacacs:
      description: null
      name: tacacs
      version_added: null
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module: {}
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 24.11.0
