---
# tasks file for vxlan_evpn

- name: dci_overlay | Set multisite ID for fabric. Ensure delay-restore is 300 seconds and advertise pip.
  cisco.nxos.nxos_config:
    lines:
      - delay-restore time 300
    parents:
      - evpn multisite border-gateway {{ vxlan['bgp']['asn'] }}
  notify: Save nxos.

- name: dci_overlay | Add multisite VIP VTEP loopback to NVE-interface.
  cisco.nxos.nxos_vxlan_vtep:
    interface: nve1
    multisite_border_gateway_interface: "{{ vxlan['dci']['if'] }}"
    state: present
  notify: Save nxos.

- name: dci_overlay | Configure remote border-leafs as neighbors. Ensure peer-type is fabric-external. Increase ttl for eBGP.  # since using loopback as source.
  cisco.nxos.nxos_bgp_global:
    config:
      as_number: "{{ vxlan['bgp']['asn'] }}"
      router_id: "{{ vxlan['rid']['ip'] }}"
      neighbors:
        - neighbor_address: "{{ vxlan_evpn_item['ip'] }}"
          remote_as: "{{ vxlan_evpn_item['asn'] }}"
          description: "{{ vxlan_evpn_item['name'] }}"
          update_source: "{{ vxlan['rid']['if'] }}"
          peer_type: fabric-external
          ebgp_multihop: 2
    state: merged
  loop: "{{ vxlan['dci']['ebgp']['neighbors'] }}"
  loop_control:
    loop_var: vxlan_evpn_item
    label: eBGP neighbor {{ vxlan_evpn_item['name'] }}
  notify: Save nxos.

- name: dci_overlay | Configure EVPN address-family for BGP neighbors.
  cisco.nxos.nxos_bgp_neighbor_address_family:
    config:
      as_number: "{{ vxlan['bgp']['asn'] }}"
      neighbors:
        - neighbor_address: "{{ vxlan_evpn_item['ip'] }}"
          address_family:
            - afi: l2vpn
              safi: evpn
              send_community:
                both: true
              rewrite_evpn_rt_asn: true
    state: merged
  loop: "{{ vxlan['dci']['ebgp']['neighbors'] }}"
  loop_control:
    loop_var: vxlan_evpn_item
    label: eBGP neighbor {{ vxlan_evpn_item['name'] }}
  notify: Save nxos.

- name: dci_overlay | Ensure dci-tracking on fabric-external interfaces.
  cisco.nxos.nxos_l3_interfaces:
    config:
      - name: "{{ vxlan_evpn_item['name'] }}"
        evpn_multisite_tracking: dci-tracking
    state: merged
  loop: "{{ vxlan['dci']['interfaces'] }}"
  loop_control:
    loop_var: vxlan_evpn_item
    label: Interface {{ vxlan_evpn_item['name'] }}
  notify: Save nxos.

- name: dci_overlay | Ensure fabric-tracking on fabric-internal interfaces.
  cisco.nxos.nxos_l3_interfaces:
    config:
      - name: "{{ vxlan_evpn_item['name'] }}"
        evpn_multisite_tracking: fabric-tracking
    state: merged
  loop: "{{ vxlan['fabric_interfaces'] }}"
  loop_control:
    loop_var: vxlan_evpn_item
    label: Interface {{ vxlan_evpn_item['name'] }}
  notify: Save nxos.

- name: dci_overlay | Ensure EVPN multisite storm suppression for DCI interfaces.
  cisco.nxos.nxos_config:
    lines:
      - evpn storm-control {{ vxlan_evpn_item }} level 5
  loop:
    - unicast
    - multicast
    - broadcast
  loop_control:
    loop_var: vxlan_evpn_item
  notify: Save nxos.
