---
# tasks file for vxlan_evpn

- name: dci_encryption | Enable MACsec feature.
  cisco.nxos.nxos_feature:
    feature: macsec
    state: enabled
  notify: Save nxos.

- name: dci_encryption | Configure MACsec keychain and key.
  cisco.nxos.nxos_command:
    commands:
      - "{{ vxlan_evpn_item }}"
  loop:
    - configure terminal
    - key chain 1 macsec
    - key 1000
    - key-octet-string {{ vxlan_evpn_macsec_key }} cryptographic-algorithm AES_256_CMAC
  loop_control:
    loop_var: vxlan_evpn_item
  no_log: true
  when: not ansible_check_mode

- name: dci_encryption | Apply MACsec policy to DCI-interfaces.
  cisco.nxos.nxos_config:
    lines:
      - macsec keychain 1 policy system-default-macsec-policy
    parents:
      - interface {{ vxlan_evpn_item['name'] }}
  loop: "{{ vxlan['dci']['interfaces'] }}"
  loop_control:
    loop_var: vxlan_evpn_item
    label: "{{ vxlan_evpn_item['name'] }}"
  notify: Save nxos.
