---
# tasks file for vxlan_evpn

- name: fabric_overlay_spine | Enable EVPN control plane for VXLAN.
  cisco.nxos.nxos_evpn_global:
    nv_overlay_evpn: true
  notify: Save nxos.

- name: fabric_overlay_spine | Configure BGP ASN, Router-ID and neighbors.
  cisco.nxos.nxos_bgp_global:
    config:
      as_number: "{{ vxlan['bgp']['asn'] }}"
      router_id: "{{ vxlan['rid']['ip'] }}"
      log_neighbor_changes: true
      neighbors:
        - neighbor_address: "{{ vxlan_evpn_item['ip'] }}"
          remote_as: "{{ vxlan['bgp']['asn'] }}"
          description: "{{ vxlan_evpn_item['name'] }}"
          update_source: "{{ vxlan['rid']['if'] }}"
    state: merged
  loop: "{{ vxlan['bgp']['neighbors'] }}"
  loop_control:
    loop_var: vxlan_evpn_item
  notify: Save nxos.

- name: fabric_overlay_spine | Configure L2VPN EVPN for BGP neighbors. Set address-family to EVPN. Define leafs as RR clients under BGP process.
  cisco.nxos.nxos_bgp_neighbor_address_family:
    config:
      as_number: "{{ vxlan['bgp']['asn'] }}"
      neighbors:
        - neighbor_address: "{{ vxlan_evpn_item['ip'] }}"
          address_family:
            - afi: l2vpn
              safi: evpn
              route_reflector_client: true
              send_community:
                both: true
    state: merged
  loop: "{{ vxlan['bgp']['neighbors'] }}"
  loop_control:
    loop_var: vxlan_evpn_item
  notify: Save nxos.
