---
# tasks file for vxlan_evpn

- name: fabric_underlay_leaf | Create and enable L3 RID and VTEP loopback fabric interfaces. Ensure interface-description.
  cisco.nxos.nxos_interfaces:
    config:
      - name: "{{ vxlan['rid']['if'] }}"
        description: "{{ vxlan['rid']['description'] }}"
        enabled: true
      - name: "{{ vxlan['vtep']['if'] }}"
        description: "{{ vxlan['vtep']['description'] }}"
        enabled: true
    state: merged
  notify: Save nxos.

- name: fabric_underlay_leaf | Enable and set physical fabric interfaces in L3 mode. Ensure jumbo MTU.
  cisco.nxos.nxos_interfaces:
    config:
      - name: "{{ vxlan_evpn_item['name'] }}"
        mode: layer3
        mtu: "{{ vxlan_evpn_mtu }}"
        enabled: true
    state: merged
  loop: "{{ vxlan['fabric_interfaces'] }}"
  loop_control:
    loop_var: vxlan_evpn_item
    label: "{{ vxlan_evpn_item['name'] }}"
  notify: Save nxos.

- name: fabric_underlay_leaf | Assign IP address and tag to L3 RID and VTEP loopback fabric interfaces.
  cisco.nxos.nxos_l3_interfaces:
    config:
      - name: "{{ vxlan['rid']['if'] }}"
        ipv4:
          - address: "{{ vxlan['rid']['ip'] }}/32"
            tag: "{{ vxlan['rid']['tag'] | default(omit) }}"
      - name: "{{ vxlan['vtep']['if'] }}"
        ipv4:
          - address: "{{ vxlan['vtep']['ip'] }}/32"
            tag: "{{ vxlan['vtep']['tag'] | default(omit) }}"
    state: merged
  notify: Save nxos.

- name: fabric_underlay_leaf | Assign secondary IP address (anycast) to loopback fabric interface used for VXLAN VTEP.  # Required for vPC.
  cisco.nxos.nxos_l3_interfaces:
    config:
      - name: "{{ vxlan['vtep']['if'] }}"
        ipv4:
          - address: "{{ vxlan['vtep']['secondary_ip'] }}/32"
            secondary: true
            tag: "{{ vxlan['vtep']['tag'] | default(omit) }}"
    state: merged
  when: vpc is defined
  notify: Save nxos.

- name: fabric_underlay_leaf | Ensure physical L3 fabric interfaces have medium p2p and IP unnumbered parameters.
  cisco.nxos.nxos_config:
    lines:
      - medium p2p
      - ip unnumbered {{ vxlan['rid']['if'] }}
    parents:
      - interface {{ vxlan_evpn_item['name'] }}
  loop: "{{ vxlan['fabric_interfaces'] }}"
  loop_control:
    loop_var: vxlan_evpn_item
    label: "{{ vxlan_evpn_item['name'] }}"
  notify: Save nxos.

- name: fabric_underlay_leaf | Set OSPF Process-ID and Router-ID and log adjacency changes.
  cisco.nxos.nxos_ospfv2:
    config:
      processes:
        - process_id: "{{ vxlan_evpn_ospf_process_id }}"
          router_id: "{{ vxlan['rid']['ip'] }}"
          log_adjacency_changes:
            detail: true
    state: merged
  notify: Save nxos.

- name: fabric_underlay_leaf | Associate L3 RID and VTEP loopback interfaces with OSFP process.
  cisco.nxos.nxos_ospf_interfaces:
    config:
      - name: "{{ vxlan['rid']['if'] }}"
        address_family:
          - afi: ipv4
            processes:
              - process_id: "{{ vxlan_evpn_ospf_process_id }}"
                area:
                  area_id: "{{ vxlan_evpn_ospf_area_id }}"
      - name: "{{ vxlan['vtep']['if'] }}"
        address_family:
          - afi: ipv4
            processes:
              - process_id: "{{ vxlan_evpn_ospf_process_id }}"
                area:
                  area_id: "{{ vxlan_evpn_ospf_area_id }}"
    state: merged
  notify: Save nxos.

- name: fabric_underlay_leaf | Associate L3 fabric p2p interfaces with OSFP process.
  cisco.nxos.nxos_ospf_interfaces:
    config:
      - name: "{{ vxlan_evpn_item['name'] }}"
        address_family:
          - afi: ipv4
            network: point-to-point
            processes:
              - process_id: "{{ vxlan_evpn_ospf_process_id }}"
                area:
                  area_id: "{{ vxlan_evpn_ospf_area_id }}"
    state: merged
  loop: "{{ vxlan['fabric_interfaces'] }}"
  loop_control:
    loop_var: vxlan_evpn_item
    label: "{{ vxlan_evpn_item['name'] }}"
  notify: Save nxos.

- name: fabric_underlay_leaf | Configure static PIM anycast RP for group range.
  cisco.nxos.nxos_pim_rp_address:
    rp_address: "{{ vxlan_evpn_pim_anycast_rp_ip }}"
    group_list: "{{ vxlan_evpn_pim_group_range }}"
    state: present
  notify: Save nxos.

- name: fabric_underlay_leaf | Ensure PIM sparse mode is running on L3 RID loopback interface.
  cisco.nxos.nxos_pim_interface:
    interface: "{{ vxlan['rid']['if'] }}"
    sparse: true
    state: present
  notify: Save nxos.

- name: fabric_underlay_leaf | Ensure PIM sparse mode is running on L3 VTEP loopback interface.
  cisco.nxos.nxos_pim_interface:
    interface: "{{ vxlan['vtep']['if'] }}"
    sparse: true
  notify: Save nxos.

- name: fabric_underlay_leaf | Ensure PIM sparse mode is running on L3 fabric interfaces.
  cisco.nxos.nxos_pim_interface:
    interface: "{{ vxlan_evpn_item['name'] }}"
    sparse: true
    state: present
  loop: "{{ vxlan['fabric_interfaces'] }}"
  loop_control:
    loop_var: vxlan_evpn_item
    label: "{{ vxlan_evpn_item['name'] }}"
  notify: Save nxos.


- name: fabric_underlay_leaf | Use vPC Peer-link as underlay backup path.  # Required for vPC.
  when: vpc is defined
  block:

    - name: fabric_underlay_leaf | Define a non-VXLAN enabled VLAN as backup routed path.
      cisco.nxos.nxos_config:
        lines:
          - system nve infra-vlans {{ vpc['nve']['vlan'] }}
      notify: Save nxos.

    - name: fabric_underlay_leaf | Create VLAN for NVE-infra.
      cisco.nxos.nxos_vlans:
        config:
          - vlan_id: "{{ vpc['nve']['vlan'] }}"
            name: BACKUP_VLAN_ROUTING_NVE_INFRA
        state: merged
      notify: Save nxos.

    - name: fabric_underlay_leaf | Create SVI for NVE-infra. Ensure jumbo MTU. Ensure interface description.
      cisco.nxos.nxos_interfaces:
        config:
          - name: "Vlan{{ vpc['nve']['vlan'] }}"
            description: "*** BACKUP VLAN ROUTING NVE-INFRA ***"
            mtu: "{{ vxlan_evpn_mtu }}"
            enabled: true
        state: merged
      notify: Save nxos.

    - name: fabric_underlay_leaf | Set IP address on SVI for NVE-infra.
      cisco.nxos.nxos_l3_interfaces:
        config:
          - name: Vlan{{ vpc['nve']['vlan'] }}
            ipv4:
              - address: "{{ vpc['nve']['ip'] }}/24"
            redirects: false
        state: merged
      notify: Save nxos.

    - name: fabric_underlay_leaf | Associate NVE-infra interface with OSFP process.
      cisco.nxos.nxos_ospf_interfaces:
        config:
          - name: "Vlan{{ vpc['nve']['vlan'] }}"
            address_family:
              - afi: ipv4
                network: point-to-point
                processes:
                  - process_id: "{{ vxlan_evpn_ospf_process_id }}"
                    area:
                      area_id: "{{ vxlan_evpn_ospf_area_id }}"
        state: merged
      notify: Save nxos.

    - name: fabric_underlay_leaf | Ensure PIM sparse mode is running on NVE-infra interface.
      cisco.nxos.nxos_pim_interface:
        interface: Vlan{{ vpc['nve']['vlan'] }}
        sparse: true
        state: present
      notify: Save nxos.
