---
galaxy_info:
  namespace: jiholland
  role_name: tacacs
  author: Jørn Ivar Holland
  description: "Ensure tacacs authentication."
  license: BSD-3-Clause
  min_ansible_version: "2.16"
  platforms:
    - name: IOS
      versions:
        - all
    - name: NXOS
      versions:
        - all
  galaxy_tags:
    - aaa
    - authentication
    - catalyst
    - cisco
    - networking
    - nexus
    - tacacs


dependencies: []
