---
# tasks file for backup

- name: backup_cisco.nxos.nxos | Backup running-config to local directory.
  cisco.nxos.nxos_config:
    backup: true
    backup_options:
      filename: "{{ __backup_filename }}"
      dir_path: "{{ __backup_temp_dir_output['path'] }}/{{ ansible_facts['date_time']['date'] }}"
  notify: Push to git.
