---
# tasks file for backup

- name: backup_cisco.nxos.nxos | Backup running-config to local directory.
  cisco.nxos.nxos_config:
    backup: true
    backup_options:
      filename: "{{ backup_filename }}"
      dir_path: "{{ backup_temp_dir_output['path'] }}/{{ backup_time }}"
  notify: Push to git.
