---
# tasks file for backup

- name: backup_cisco.ios.ios | Backup running-config to local directory.
  cisco.ios.ios_config:
    backup: true
    backup_options:
      filename: "{{ __backup_filename }}"
      dir_path: "{{ __backup_temp_dir_output['path'] }}/{{ ansible_facts['date_time']['date'] }}"
  notify: Push to git.
