---
# Argument specification file for backup

argument_specs:
  main:
    options:

      backup_git_repo:
        type: str
        required: true

      backup_git_version:
        type: str
        default: main

      backup_git_accept_newhostkey:
        type: bool
        default: true
