---
# tasks file for tacacs

- name: configure_cisco.ios.ios | Set tacacs server hosts and group.
  cisco.ios.ios_config:
    src: tacacs_ios.j2
  no_log: true

- name: configure_cisco.ios.ios | Configure tacacs authentication, authorization and accounting.
  cisco.ios.ios_config:
    lines:
      - aaa new-model
      - aaa authentication login default group {{ tacacs_group }} local
      - aaa authentication enable default group {{ tacacs_group }} enable
      - aaa authorization exec default group {{ tacacs_group }} local
      - aaa authorization console
      - no aaa accounting system guarantee-first
      - aaa accounting exec default {{ tacacs_accounting_record }} group {{ tacacs_group }}
      - aaa accounting commands 15 default {{ tacacs_accounting_record }} group {{ tacacs_group }}
  notify: Save ios.

- name: configure_cisco.ios.ios | Get tacacs-servers.
  cisco.ios.ios_command:
    commands:
      - show run aaa tacacs-server | include tacacs server
  register: tacacs_servers_output

- name: configure_cisco.ios.ios | Remove obsolete tacacs-servers.
  cisco.ios.ios_config:
    src: tacacs_obsolete_ios.j2
  notify: Save ios.
