---
# tasks file for tacacs

- name: configure_cisco.nxos.nxos | Set tacacs server hosts and group.
  cisco.nxos.nxos_config:
    src: tacacs_nxos.j2
  no_log: true

- name: configure_cisco.nxos.nxos | Configure tacacs authentication and accounting.
  cisco.nxos.nxos_config:
    lines:
      - aaa authentication login default group {{ tacacs_group }} local
      - aaa authentication login console group {{ tacacs_group }} local
      - aaa authentication login error-enable
      - aaa accounting default group {{ tacacs_group }}
  notify: Save nxos.

- name: configure_cisco.nxos.nxos | Get tacacs-servers.
  cisco.nxos.nxos_command:
    commands:
      - show run tacacs+ | include tacacs-server
  register: tacacs_servers_output

- name: configure_cisco.nxos.nxos | Remove obsolete tacacs-servers.
  cisco.nxos.nxos_config:
    src: tacacs_obsolete_nxos.j2
  notify: Save nxos.
