---
# tasks file for tacacs

- name: configure_cisco.nxos.nxos | Enable tacacs feature.
  cisco.nxos.nxos_feature:
    feature: tacacs
    state: enabled
  notify: Save nxos.

- name: configure_cisco.nxos.nxos | Set tacacs server hosts and group.
  cisco.nxos.nxos_config:
    src: tacacs_nxos.j2
  no_log: true

- name: configure_cisco.nxos.nxos | Configure tacacs authentication and accounting.
  cisco.nxos.nxos_config:
    lines:
      - "aaa authentication login default group {{ tacacs_group }} local"
      - "aaa authentication login console group {{ tacacs_group }} local"
      - "aaa authentication login error-enable"
      - "aaa accounting default group {{ tacacs_group }}"
  notify: Save nxos.

- name: configure_cisco.nxos.nxos | Get tacacs-servers.
  cisco.nxos.nxos_command:
    commands:
      - "show run tacacs+ | include tacacs-server"
  register: __tacacs_servers_output

- name: configure_cisco.nxos.nxos | Remove obsolete tacacs-servers.
  block:

    - name: configure_cisco.nxos.nxos | Remove obsolete tacacs-servers and remove from aaa group.
      cisco.nxos.nxos_config:
        src: tacacs_obsolete_nxos.j2
      notify: Save nxos.

  rescue:

    - name: configure_cisco.nxos.nxos | Remove obsolete tacacs-servers.
      cisco.nxos.nxos_config:
        lines:
          - "no tacacs-server host {{ tacacs_item.split(' ')[2] }}"
      when: tacacs_item.split(' ')[2] is not in (tacacs_servers | map(attribute='ip'))
      loop: "{{ __tacacs_servers_output['stdout_lines'][0] }}"
      loop_control:
        loop_var: tacacs_item
      notify: Save nxos.
