---
# defaults file for software

# software_version: 17.06.05
# software_image: cat9k_iosxe.17.06.05.SPA.bin

# software_vrf: management

# software_server: 192.0.2.10

software_server_path: /var/lib/tftpboot
software_server_user: "{{ ansible_user }}"
software_server_password: "{{ ansible_password }}"

software_upload_timeout: 3600
software_install_timeout: "{{ (software_issu is eq('no')) | ansible.builtin.ternary('1080', '1800') }}"
software_install_rescue_timeout: 180
software_reboot_delay: 30
software_reboot_timeout: 900

software_issu: "no"

# Used when scheduling the upgrade.
software_playbook_name: software_upgrade_playbook.yml
software_target: "{{ target }}"
