---
# defaults file for software

# The server where the compliant images are stored.
software_tftp_server: 10.10.10.10

software_upload_timeout: 3600
software_install_timeout: 1080
software_install_issu_timeout: 1800
software_install_rescue_timeout: 180
software_reboot_delay: 30
software_reboot_timeout: 900

# Used when scheduling the upgrade.
software_playbook_name: playbook.yml

# Upgrade using In Service Software Upgrade (ISSU).
software_issu: false

# Vrf used for the tftp server.
# software_vrf: management

# software_version: 17.09.04
# software_image: cat9k_iosxe.17.09.04.SPA.bin
