---
# Argument specification file for software

argument_specs:
  main:
    options:

      software_version:
        type: str
        required: true

      software_image:
        type: str
        required: true

      software_server:
        description: "The server where the image are stored."
        type: str
        required: true

      software_issu:
        description: "Install using In Service Software Upgrade (ISSU) or not."
        type: str
        default: "no"
        choices:
          - "no"
          - "yes"
