galaxy_info:
  role_name: banner
  author: Jørn Ivar Holland
  description: Ensure banner.
  license: BSD-3-Clause
  min_ansible_version: '2.11'
  platforms:
    - name: IOS
      versions:
        - all
    - name: NXOS
      versions:
        - all
  galaxy_tags:
    - networking
    - cisco
    - banner

dependencies: []
