---
# tasks file for interface_description

- name: configure_cisco.ios.ios | Gather interface facts.
  cisco.ios.ios_facts:
    gather_subset:
      - interfaces
  vars:
    ansible_command_timeout: "{{ interface_description_timeout }}"
    ansible_connect_timeout: "{{ interface_description_timeout }}"

- name: configure_cisco.ios.ios | Set interface description.
  cisco.ios.ios_interfaces:
    config: "{{ interface_description_ios }}"
    state: merged
  when: interface_description_ios | length is gt(0)
  notify: Save ios.
