---
# tasks file for interface_description

- name: configure_cisco.nxos.nxos | Gather interface facts.
  cisco.nxos.nxos_facts:
    gather_subset:
      - interfaces
  vars:
    ansible_command_timeout: 60

- name: configure_cisco.nxos.nxos | Set interface description.
  cisco.nxos.nxos_interfaces:
    config: "{{ interface_description_nxos }}"
    state: merged
  when: interface_description_nxos | length is gt(0)
  notify: Save nxos.
