---
# tasks file for interface_description

- name: configure_cisco.nxos.nxos | Gather interface facts.
  cisco.nxos.nxos_facts:
    gather_subset:
      - interfaces
  vars:
    ansible_command_timeout: 60

- name: configure_cisco.nxos.nxos | Set interface description.
  cisco.nxos.nxos_config:
    lines:
      - description {{ interface_description_item['value'][0]['host'] }} via {{ interface_description_item['value'][0]['port'] }}
    parents:
      - interface {{ interface_description_item['key'] }}
  loop: "{{ ansible_facts['net_neighbors'] | dict2items }}"
  loop_control:
    loop_var: interface_description_item
    label: "{{ interface_description_item['key'] }}"
  notify: Save nxos.
