---
# defaults file for interface_description

# Timeout in seconds for gathering facts.
interface_description_timeout: 60

interface_description_ios: "{{ lookup('ansible.builtin.template', 'interface_description_ios.j2') | ansible.builtin.from_yaml }}"
interface_description_nxos: "{{ lookup('ansible.builtin.template', 'interface_description_nxos.j2') | ansible.builtin.from_yaml }}"
