---
# handlers file for backup

- name: Push to git.
  # noqa command-instead-of-module
  ansible.builtin.command:
    cmd: "{{ backup_item }}"
    chdir: "{{ __backup_temp_dir_output['path'] }}/{{ ansible_facts['date_time']['date'] }}"
  loop:
    - git add .
    - git commit -m 'Backup created at {{ ansible_facts['date_time']['date'] }}.'
    - git push origin {{ backup_git_version }}
  loop_control:
    loop_var: backup_item
  changed_when: true
  delegate_to: localhost
  run_once: true

- name: Remove temporary backup directory from localhost.
  ansible.builtin.file:
    path: "{{ __backup_temp_dir_output['path'] }}"
    state: absent
  delegate_to: localhost
  run_once: true
  check_mode: false
